using System.Net;
using System.Net.Http.Json;
using Api.Dtos;
using Domain.Containers;
using Domain.ContainerTypes;
using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using Tests.Common;
using Tests.Data.Containers;
using Tests.Data.ContainerTypes;

namespace Api.Tests.Integration.Containers;

// Тести для створення контейнерів (POST endpoint)
public class ContainersCreateTests : BaseIntegrationTest, IAsyncLifetime
{
    private const string BaseRoute = "containers";

    private readonly ContainerType _testContainerType = ContainerTypeData.FirstTestContainerType();
    private Container? _existingContainer;

    public ContainersCreateTests(IntegrationTestWebFactory factory) : base(factory)
    {
    }

    // Повинен створити новий контейнер
    [Fact]
    public async Task ShouldCreateContainer()
    {
        // Arrange
        var request = ContainerData.CreateTestContainerDto(_testContainerType.Id);

        // Act
        var response = await Client.PostAsJsonAsync(BaseRoute, request);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.OK);
        var containerDto = await response.ToResponseModel<ContainerDto>();

        containerDto.Code.Should().Be(request.Code);
        containerDto.Name.Should().Be(request.Name);
        containerDto.Volume.Should().Be(request.Volume);
        containerDto.Unit.Should().Be(request.Unit);
        containerDto.ContainerTypeId.Should().Be(request.ContainerTypeId);
        containerDto.Status.Should().Be(ContainerStatus.Empty.ToString());
        containerDto.Id.Should().BeGreaterThan(0);

        var dbContainer = await Context.Containers
            .FirstOrDefaultAsync(c => c.Id == containerDto.Id);

        dbContainer.Should().NotBeNull();
        dbContainer!.Code.Should().Be(request.Code);
        dbContainer.Unit.Should().Be(request.Unit);
        dbContainer.Status.Should().Be(ContainerStatus.Empty);
    }

    // Повинен створити контейнер з null Meta
    [Fact]
    public async Task ShouldCreateContainerWithNullMeta()
    {
        // Arrange
        var uniqueId = Guid.NewGuid().ToString()[..8];
        var request = new CreateContainerDto
        {
            Code = $"QR-{uniqueId}-NULL",
            Name = "Test-NullMeta-Container",
            Volume = 50.0m,
            Unit = "л",
            ContainerTypeId = _testContainerType.Id,
            Meta = null
        };

        // Act
        var response = await Client.PostAsJsonAsync(BaseRoute, request);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.OK);
        var containerDto = await response.ToResponseModel<ContainerDto>();
        containerDto.Meta.Should().BeNull();
    }

    // Повинен створити контейнер з автоматично згенерованим кодом
    [Fact]
    public async Task ShouldCreateContainerWithAutoGeneratedCode()
    {
        // Arrange
        var request = ContainerData.CreateTestContainerDtoWithAutoCode(_testContainerType.Id);

        // Act
        var response = await Client.PostAsJsonAsync(BaseRoute, request);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.OK);
        var containerDto = await response.ToResponseModel<ContainerDto>();

        containerDto.Code.Should().NotBeNullOrEmpty();
        containerDto.Code.Should().StartWith(_testContainerType.CodePrefix);
        containerDto.Name.Should().Be(request.Name);

        var dbContainer = await Context.Containers
            .FirstOrDefaultAsync(c => c.Id == containerDto.Id);
        dbContainer.Should().NotBeNull();
    }

    // Не повинен створити контейнер з дублікатом коду
    [Fact]
    public async Task ShouldNotCreateContainerBecauseDuplicateCode()
    {
        // Arrange
        var request = new CreateContainerDto
        {
            Code = _existingContainer!.Code,
            Name = "Test-Duplicate-Container",
            Volume = 50.0m,
            Unit = "л",
            ContainerTypeId = _testContainerType.Id,
            Meta = null
        };

        // Act
        var response = await Client.PostAsJsonAsync(BaseRoute, request);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.Conflict);
    }

    // Не повинен створити контейнер з порожньою назвою
    [Theory]
    [InlineData("")]
    [InlineData(null)]
    public async Task ShouldNotCreateContainerBecauseEmptyName(string? name)
    {
        // Arrange
        var uniqueId = Guid.NewGuid().ToString()[..8];
        var request = new CreateContainerDto
        {
            Code = $"QR-{uniqueId}",
            Name = name!,
            Volume = 50.0m,
            Unit = "л",
            ContainerTypeId = _testContainerType.Id,
            Meta = null
        };

        // Act
        var response = await Client.PostAsJsonAsync(BaseRoute, request);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.BadRequest);
    }

    // Не повинен створити контейнер з порожньою одиницею виміру
    [Theory]
    [InlineData("")]
    [InlineData(null)]
    public async Task ShouldNotCreateContainerBecauseEmptyUnit(string? unit)
    {
        // Arrange
        var uniqueId = Guid.NewGuid().ToString()[..8];
        var request = new CreateContainerDto
        {
            Code = $"QR-{uniqueId}",
            Name = "Test-Container",
            Volume = 50.0m,
            Unit = unit!,
            ContainerTypeId = _testContainerType.Id,
            Meta = null
        };

        // Act
        var response = await Client.PostAsJsonAsync(BaseRoute, request);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.BadRequest);
    }

    // Не повинен створити контейнер з об'ємом 0 або негативним
    [Theory]
    [InlineData(0)]
    [InlineData(-10)]
    public async Task ShouldNotCreateContainerBecauseVolumeZeroOrNegative(decimal volume)
    {
        // Arrange
        var uniqueId = Guid.NewGuid().ToString()[..8];
        var request = new CreateContainerDto
        {
            Code = $"QR-{uniqueId}",
            Name = "Valid-Name",
            Volume = volume,
            Unit = "л",
            ContainerTypeId = _testContainerType.Id,
            Meta = null
        };

        // Act
        var response = await Client.PostAsJsonAsync(BaseRoute, request);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.BadRequest);
    }

    // Не повинен створити контейнер з занадто довгим кодом
    [Fact]
    public async Task ShouldNotCreateContainerBecauseCodeTooLong()
    {
        // Arrange
        var tooLongCode = new string('C', 51);
        var request = new CreateContainerDto
        {
            Code = tooLongCode,
            Name = "Test-Long-Code",
            Volume = 50.0m,
            Unit = "л",
            ContainerTypeId = _testContainerType.Id,
            Meta = null
        };

        // Act
        var response = await Client.PostAsJsonAsync(BaseRoute, request);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.BadRequest);
    }

    // Не повинен створити контейнер з занадто довгою назвою
    [Fact]
    public async Task ShouldNotCreateContainerBecauseNameTooLong()
    {
        // Arrange
        var uniqueId = Guid.NewGuid().ToString()[..8];
        var tooLongName = new string('N', 101);
        var request = new CreateContainerDto
        {
            Code = $"QR-{uniqueId}-LONG",
            Name = tooLongName,
            Volume = 50.0m,
            Unit = "л",
            ContainerTypeId = _testContainerType.Id,
            Meta = null
        };

        // Act
        var response = await Client.PostAsJsonAsync(BaseRoute, request);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.BadRequest);
    }

    // Не повинен створити контейнер з неіснуючим типом контейнера
    [Fact]
    public async Task ShouldNotCreateContainerBecauseContainerTypeNotFound()
    {
        // Arrange
        var uniqueId = Guid.NewGuid().ToString()[..8];
        var request = new CreateContainerDto
        {
            Code = $"QR-{uniqueId}",
            Name = "Test-Container",
            Volume = 50.0m,
            Unit = "л",
            ContainerTypeId = 999999,
            Meta = null
        };

        // Act
        var response = await Client.PostAsJsonAsync(BaseRoute, request);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.NotFound);
    }

    // Не повинен створити контейнер з ContainerTypeId = 0
    [Fact]
    public async Task ShouldNotCreateContainerBecauseZeroContainerTypeId()
    {
        // Arrange
        var uniqueId = Guid.NewGuid().ToString()[..8];
        var request = new CreateContainerDto
        {
            Code = $"QR-{uniqueId}",
            Name = "Test-Container",
            Volume = 50.0m,
            Unit = "л",
            ContainerTypeId = 0,
            Meta = null
        };

        // Act
        var response = await Client.PostAsJsonAsync(BaseRoute, request);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.BadRequest);
    }

    public async Task InitializeAsync()
    {
        await Context.ContainerTypes.AddAsync(_testContainerType);
        await SaveChangesAsync();

        _existingContainer = ContainerData.FirstTestContainer(_testContainerType.Id);
        await Context.Containers.AddAsync(_existingContainer);
        await SaveChangesAsync();
    }

    public async Task DisposeAsync()
    {
        Context.Containers.RemoveRange(Context.Containers);
        Context.ContainerTypes.RemoveRange(Context.ContainerTypes);

        await SaveChangesAsync();
    }
}
