// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContainerTypeProductType", b =>
                {
                    b.Property<int>("AllowedProductTypesId")
                        .HasColumnType("integer")
                        .HasColumnName("allowed_product_types_id");

                    b.Property<int>("CompatibleContainerTypesId")
                        .HasColumnType("integer")
                        .HasColumnName("compatible_container_types_id");

                    b.HasKey("AllowedProductTypesId", "CompatibleContainerTypesId")
                        .HasName("pk_container_type_allowed_products");

                    b.HasIndex("CompatibleContainerTypesId")
                        .HasDatabaseName("ix_container_type_allowed_products_compatible_container_types_id");

                    b.ToTable("ContainerTypeAllowedProducts", (string)null);
                });

            modelBuilder.Entity("Domain.ContainerTypes.ContainerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodePrefix")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code_prefix");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("DefaultUnit")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("default_unit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<string>("Meta")
                        .HasColumnType("jsonb")
                        .HasColumnName("meta");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_container_types");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_container_types_created_by_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_container_types_is_deleted");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("ix_container_types_last_modified_by_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_container_types_name")
                        .HasFilter("is_deleted = false");

                    b.ToTable("container_types", (string)null);
                });

            modelBuilder.Entity("Domain.Containers.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<int>("ContainerTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("container_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("CurrentExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_expiration_date");

                    b.Property<int?>("CurrentFillId")
                        .HasColumnType("integer")
                        .HasColumnName("current_fill_id");

                    b.Property<DateTime?>("CurrentFilledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_filled_at");

                    b.Property<int?>("CurrentProductId")
                        .HasColumnType("integer")
                        .HasColumnName("current_product_id");

                    b.Property<int?>("CurrentProductTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("current_product_type_id");

                    b.Property<DateTime?>("CurrentProductionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_production_date");

                    b.Property<decimal?>("CurrentQuantity")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("current_quantity");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastEmptiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_emptied_at");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<int?>("LastProductId")
                        .HasColumnType("integer")
                        .HasColumnName("last_product_id");

                    b.Property<int?>("LastProductTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("last_product_type_id");

                    b.Property<string>("Meta")
                        .HasColumnType("jsonb")
                        .HasColumnName("meta");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Empty")
                        .HasColumnName("status");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("volume");

                    b.HasKey("Id")
                        .HasName("pk_containers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_containers_code")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("ContainerTypeId")
                        .HasDatabaseName("ix_containers_container_type_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_containers_created_by_id");

                    b.HasIndex("CurrentFillId")
                        .IsUnique()
                        .HasDatabaseName("ix_containers_current_fill_id");

                    b.HasIndex("CurrentProductId")
                        .HasDatabaseName("ix_containers_current_product_id");

                    b.HasIndex("CurrentProductTypeId")
                        .HasDatabaseName("ix_containers_current_product_type_id");

                    b.HasIndex("CurrentProductionDate")
                        .HasDatabaseName("ix_containers_current_production_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_containers_is_deleted");

                    b.HasIndex("LastEmptiedAt")
                        .HasDatabaseName("ix_containers_last_emptied_at");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("ix_containers_last_modified_by_id");

                    b.HasIndex("LastProductId")
                        .HasDatabaseName("ix_containers_last_product_id");

                    b.HasIndex("LastProductTypeId")
                        .HasDatabaseName("ix_containers_last_product_type_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_containers_status");

                    b.ToTable("containers", (string)null);
                });

            modelBuilder.Entity("Domain.Containers.ContainerFill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContainerId")
                        .HasColumnType("integer")
                        .HasColumnName("container_id");

                    b.Property<Guid?>("EmptiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("emptied_by_user_id");

                    b.Property<DateTime?>("EmptiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("emptied_date");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<Guid>("FilledByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("filled_by_user_id");

                    b.Property<DateTime>("FilledDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("filled_date");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("production_date");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("quantity");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_container_fills");

                    b.HasIndex("ContainerId")
                        .HasDatabaseName("ix_container_fills_container_id");

                    b.HasIndex("EmptiedByUserId")
                        .HasDatabaseName("ix_container_fills_emptied_by_user_id");

                    b.HasIndex("EmptiedDate")
                        .HasDatabaseName("ix_container_fills_emptied_date");

                    b.HasIndex("ExpirationDate")
                        .HasDatabaseName("ix_container_fills_expiration_date");

                    b.HasIndex("FilledByUserId")
                        .HasDatabaseName("ix_container_fills_filled_by_user_id");

                    b.HasIndex("FilledDate")
                        .HasDatabaseName("ix_container_fills_filled_date");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_container_fills_product_id");

                    b.HasIndex("ProductionDate")
                        .HasDatabaseName("ix_container_fills_production_date");

                    b.ToTable("container_fills", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middle_name");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_users_created_by_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("ix_users_last_modified_by_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user_invitations");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_user_invitations_created_by_id");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_user_invitations_email");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("ix_user_invitations_last_modified_by_id");

                    b.ToTable("user_invitations", (string)null);
                });

            modelBuilder.Entity("Domain.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("product_type_id");

                    b.Property<int?>("ShelfLifeDays")
                        .HasColumnType("integer")
                        .HasColumnName("shelf_life_days");

                    b.Property<int?>("ShelfLifeHours")
                        .HasColumnType("integer")
                        .HasColumnName("shelf_life_hours");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_products_created_by_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_products_is_deleted");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("ix_products_last_modified_by_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_products_name");

                    b.HasIndex("ProductTypeId")
                        .HasDatabaseName("ix_products_product_type_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Domain.Products.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<string>("Meta")
                        .HasColumnType("jsonb")
                        .HasColumnName("meta");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ShelfLifeDays")
                        .HasColumnType("integer")
                        .HasColumnName("shelf_life_days");

                    b.Property<int?>("ShelfLifeHours")
                        .HasColumnType("integer")
                        .HasColumnName("shelf_life_hours");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_product_types");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_product_types_created_by_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_product_types_is_deleted");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("ix_product_types_last_modified_by_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_product_types_name")
                        .HasFilter("is_deleted = false");

                    b.ToTable("product_types", (string)null);
                });

            modelBuilder.Entity("ContainerTypeProductType", b =>
                {
                    b.HasOne("Domain.Products.ProductType", null)
                        .WithMany()
                        .HasForeignKey("AllowedProductTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_container_type_allowed_products_product_types_allowed_product_");

                    b.HasOne("Domain.ContainerTypes.ContainerType", null)
                        .WithMany()
                        .HasForeignKey("CompatibleContainerTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_container_type_allowed_products_container_types_compatible_con");
                });

            modelBuilder.Entity("Domain.ContainerTypes.ContainerType", b =>
                {
                    b.HasOne("Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_container_types_users_created_by_id");

                    b.HasOne("Domain.Entities.User", "LastModifiedByUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_container_types_users_last_modified_by_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastModifiedByUser");
                });

            modelBuilder.Entity("Domain.Containers.Container", b =>
                {
                    b.HasOne("Domain.ContainerTypes.ContainerType", "ContainerType")
                        .WithMany()
                        .HasForeignKey("ContainerTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_containers_container_types_id");

                    b.HasOne("Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_containers_users_created_by_id");

                    b.HasOne("Domain.Products.Product", "CurrentProduct")
                        .WithMany()
                        .HasForeignKey("CurrentProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_containers_products_current_product_id");

                    b.HasOne("Domain.Entities.User", "LastModifiedByUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_containers_users_last_modified_by_id");

                    b.Navigation("ContainerType");

                    b.Navigation("CreatedByUser");

                    b.Navigation("CurrentProduct");

                    b.Navigation("LastModifiedByUser");
                });

            modelBuilder.Entity("Domain.Containers.ContainerFill", b =>
                {
                    b.HasOne("Domain.Containers.Container", "Container")
                        .WithMany()
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_container_fills_containers_id");

                    b.HasOne("Domain.Entities.User", "EmptiedByUser")
                        .WithMany()
                        .HasForeignKey("EmptiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_container_fills_users_emptied_by_user_id");

                    b.HasOne("Domain.Entities.User", "FilledByUser")
                        .WithMany()
                        .HasForeignKey("FilledByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_container_fills_users_filled_by_user_id");

                    b.HasOne("Domain.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_container_fills_products_id");

                    b.Navigation("Container");

                    b.Navigation("EmptiedByUser");

                    b.Navigation("FilledByUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_users_created_by_id");

                    b.HasOne("Domain.Entities.User", "LastModifiedByUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_users_last_modified_by_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastModifiedByUser");
                });

            modelBuilder.Entity("Domain.Entities.UserInvitation", b =>
                {
                    b.HasOne("Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_invitations_users_created_by_id");

                    b.HasOne("Domain.Entities.User", "LastModifiedByUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_invitations_users_last_modified_by_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastModifiedByUser");
                });

            modelBuilder.Entity("Domain.Products.Product", b =>
                {
                    b.HasOne("Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_products_users_created_by_id");

                    b.HasOne("Domain.Entities.User", "LastModifiedByUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_products_users_last_modified_by_id");

                    b.HasOne("Domain.Products.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_product_types_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastModifiedByUser");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Domain.Products.ProductType", b =>
                {
                    b.HasOne("Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_product_types_users_created_by_id");

                    b.HasOne("Domain.Entities.User", "LastModifiedByUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_product_types_users_last_modified_by_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastModifiedByUser");
                });
#pragma warning restore 612, 618
        }
    }
}
